# Generated by Django 5.2.16 on 2026-07-13 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('english_words', models.BooleanField(default=False)),
                ('english_speaking', models.BooleanField(default=False)),
                ('reading', models.BooleanField(default=False)),
                ('interview', models.BooleanField(default=False)),
                ('python_topic', models.BooleanField(default=False)),
                ('coding_problem', models.BooleanField(default=False)),
                ('mini_program', models.BooleanField(default=False)),
                ('html_css_js', models.BooleanField(default=False)),
                ('ui_component', models.BooleanField(default=False)),
                ('sql_django', models.BooleanField(default=False)),
                ('project', models.BooleanField(default=False)),
                ('github', models.BooleanField(default=False)),
                ('typing', models.BooleanField(default=False)),
                ('notes', models.BooleanField(default=False)),
                ('revision', models.BooleanField(default=False)),
                ('sleep', models.BooleanField(default=False)),
                ('achievement', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('tomorrow_focus', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
